spring:
  application:
    name: login-jwt
  datasource:
    url: jdbc:postgresql://localhost:5433/loginSpring
    username: postgres
    password: Partyrock123*
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update